
version: 2

models:
  - name: DIM_Lines
    description: "lignes de transport TAG"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          
  - name: DIM_Stops
    description: "Arrets"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null